mapTitle: City of Garden Grove Community Development
baseMaps:
  - source: '//ggcity.org/tileserver/styles/standard/{z}/{x}/{y}.png'
    format: XYZ
    attribution: '<a href="https://ggcity.org/maps" target="_blank">GGCity</a> | \n
      &copy; <a href="http://openmaptiles.org/" target="_blank">OpenMapTiles</a> \n
      &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors \n
      &copy; <a href="https://github.com/microsoft/USBuildingFootprints/blob/master/LICENSE" target="_blank">Microsoft</a>'
    edgeBufferTiles: 1
    maxZoom: 20
  - source: '//ggcity.org/geoserver/gwc/service/wms'
    layers: 'gis:aerials_latest'
    format: WMS
    transparent: false
    maxZoom: 20
    maxNativeZoom: 20

wmsDefaultSource: //ggcity.org/geoserver/gis/wms

overlayMaps:
  - machineName: cases
    name: Open Cases 
    description: 'Building, Code Enforcement, Planning'
    layers:
      alwaysOn:
        - machineName: 'gis:city.address_labels'
      exclusives:
        - machineName: 'gis:building.open_permits'
          source: //ggcity.org/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:building.open_permits&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Open Building Permits
          type: geojson
          radius: 10
          weight: 0
          fillColor: '#42d7f4'
          fillOpacity: 0.8 
          maxClusterRadius: 140
          identify: true
          cluster: true
          visible: true 
        - machineName: 'gis:building.code_violations'
          source: //ggcity.org/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:building.code_violations&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Building Code Violations 
          type: geojson
          radius: 10
          weight: 0
          fillColor: '#f4ac41'
          fillOpacity: 0.8 
          maxClusterRadius: 50 
          identify: true
          cluster: true
        - machineName: 'gis:building.scheduled_inspections'
          source: //ggcity.org/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:building.scheduled_inspections&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Scheduled Building Inspections
          type: geojson
          radius: 10
          weight: 0
          fillColor: '#39b261'
          fillOpacity: 0.8 
          maxClusterRadius: 25 
          identify: true
          cluster: true
        - machineName: 'gis:code.violations'
          source: //ggcity.org/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:code.violations&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Code Enforcement Violations
          type: geojson
          radius: 10 
          weight: 0
          fillColor: '#f46d41'
          fillOpacity: 0.8 
          maxClusterRadius: 60 
          identify: true
          cluster: true
        - machineName: 'gis:planning.open_cases'
          source: //ggcity.org/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:planning.open_cases&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Open Planning Cases
          type: geojson
          radius: 10 
          weight: 0
          fillColor: '#b241f4'
          fillOpacity: 0.8 
          maxClusterRadius: 30 
          identify: true
          cluster: true
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
