mapTitle: City of Garden Grove Data Portal
baseMaps:
  - source: '//ggcity.org/tileserver/styles/standard-no-boundary/{z}/{x}/{y}.png'
    format: XYZ
    attribution: '<a href="https://ggcity.org/maps" target="_blank">GGCity</a> | \n
      &copy; <a href="http://openmaptiles.org/" target="_blank">OpenMapTiles</a> \n
      &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors \n
      &copy; <a href="https://github.com/microsoft/USBuildingFootprints/blob/master/LICENSE" target="_blank">Microsoft</a>'
    edgeBufferTiles: 1
    maxZoom: 20
  - source: '//ggcity.org/geoserver/gwc/service/wms'
    layers: 'gis:aerials'
    # fix format to use image/png so we can use aerials_latest
    format: WMS
    transparent: false
    maxZoom: 20
    maxNativeZoom: 20

wmsDefaultSource: //ggcity.org/geoserver/gis/wms

overlayMaps:
  - machineName: city
    name: General City Layers
    description: 'Atlas, City Council Districts, Benchmarks, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:city.parcel_atlas'
          name: Atlas Sheets
        - machineName: 'gis:city.benchmarks'
          name: Benchmarks 
        - machineName: 'gis:city.bicycle_corridors'
          name: Bike Master Plan Corridors
        - machineName: 'gis:city.boundary'
          name: City Boundary 
        - machineName: 'gis:city.council_districts'
          name: City Council Districts
          visible: true 
        - machineName: 'gis:city.city_owned_parcels'
          name: City-Owned Parcels
        - machineName: 'gis:fire.stations'
          name: Fire Stations
        - machineName: 'gis:city.neighborhoods'
          name: Neighborhoods & Business Districts
        - machineName: 'gis:city.parks'
          name: Parks
        - machineName: 'gis:city.schools'
          name: Schools

  - machineName: building
    name: Building Case Layers 
    description: 'Violations, Open Permits, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:building.code_violations'
          name: Code Violations 
          visible: true
        - machineName: 'gis:building.open_permits'
          name: Open Permits

  - machineName: code_enforcement
    name: Code Enforcement Layers 
    description: 'Violations, Coverage, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:code.officer_coverage'
          name: Coverage 
          visible: true
        - machineName: 'gis:code.violations'
          name: Violations

  - machineName: flood
    name: Flood Layers 
    description: 'FEMA LOMAs, FEMA SFHAs, Flood Prone Locations, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:city.fema_lomas'
          name: FEMA LOMAs 
          visible: true
        - machineName: 'gis:county.fema_sfhas'
          name: FEMA SFHAs

  - machineName: county
    name: Orange County Layers 
    description: 'Boundaries, Parcels, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 11
    resetViewOnSelect: true
    layers:
      alwaysOn: 
        - machineName: 'gis:city.address_labels' 
      exclusives:
        - machineName: 'gis:county.octa_bus_stops'
          name: OCTA Bus Stops
        - machineName: 'gis:county.city_boundaries'
          name: City Boundaries 
          visible: true
        - machineName: 'gis:county.census_tracts'
          name: Census Tracts
        - machineName: 'gis:county.college_districts'
          name: College Districts
        - machineName: 'gis:county.elementary_school_districts'
          name: Elementary School Districts
        - machineName: 'gis:county.high_school_districts'
          name: High School Districts
        - machineName: 'gis:county.unified_school_districts'
          name: Unified School Districts
        - machineName: 'gis:county.parcels'
          name: Parcels

  - machineName: planning 
    name: Planning Layers
    description: 'Zoning, Land Use, Redevelopment, CDBG'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:planning.cdbg'
          name: CDBG 
        - machineName: 'gis:planning.land_use'
          name: Land Use 
        - machineName: 'gis:planning.open_cases'
          name: Open Cases 
        - machineName: 'gis:planning.zoning'
          name: Zoning 
          visible: true 

  - machineName: property 
    name: Property Layers
    description: 'Addresses, Buildings, Parcels'
    initialCenter:
      - 33.775687
      - -117.936863
    initialZoom: 18
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      optionals:
        - machineName: 'gis:city.public_addresses'
          name: Addresses
          visible: true 
        - machineName: 'gis:city.buildings'
          name: Buildings
          visible: true 
        - machineName: 'gis:city.parcels'
          name: Parcels
          visible: true 

  - machineName: pw
    name: Public Works Layers
    description: 'Trash, Street Sweeping, etc'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:city.boundary'
      exclusives:
        - machineName: 'gis:pw.street_sweeping'
          name: Street Sweeping
          visible: true
        - machineName: 'gis:pw.trash_pickup'
          name: Trash Pickup

  - machineName: state
    name: State Layers
    description: 'Assembly Districts, Congressional Districts, Senate Districts'
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 11
    resetViewOnSelect: true
    layers:
      alwaysOn:
        - machineName: 'gis:county.city_boundaries'
      exclusives:
        - machineName: 'gis:state.assembly_districts'
          name: CA Assembly Districts
          visible: true 
        - machineName: 'gis:state.congress_districts'
          name: CA Congressional Districts
        - machineName: 'gis:state.senate_districts'
          name: CA Senate Districts
